### ISSUE TITLE
how to use fcm push notification on TWA apk

### ISSUE THREAD

**Issue by Biswajitdeveloper** [GoogleChromeLabs/svgomg-twa#102]
I need to convert PWA to apk . I use this project for building apk . But in apk fcm push notification not working, also user device token not save in database or cookies. please tell me how can I do this?

**Comment by andreban** [comment]
@Biswajitdeveloper the best place to ask this question is on StackOverflow, under the https://stackoverflow.com/questions/tagged/trusted-web-activity/ tag. Would you mind re-posting the question there? I'm closing the issue here, as this is somewhat unrelated to this repo (the demo in it doesn't use push notifications).
