### ISSUE TITLE
Does TWA notification delegation handle sound also?

### ISSUE THREAD

**Issue by jitendra1607** [GoogleChromeLabs/svgomg-twa#103]
Does TWA notification delegation handle sound also as defined in PWA service worker ? How notification sound works?

**Comment by beverloo** [comment]
The default behaviour will match what happens when receiving the same notification in Chrome without having the PWA installed.

Regarding `sound`, the Web Notification API does not provide an option to configure your own sound. Instead, it has a `silent` flag, but we stopped supporting that flag on Android O due to changes in the system notification center that no longer allow setting this on a per-notification basis. It is supported on other platforms.

You can change this behaviour for a TWA by overriding the `onNotifiyNotificationWithChannel` method in the `TrustedWebActiviyService`:

https://developer.android.com/reference/androidx/browser/trusted/TrustedWebActivityService#onNotifyNotificationWithChannel(java.lang.String,%20int,%20android.app.Notification,%20java.lang.String)

But, again, do note that sounds have to be set when you _create the channel_, not when you _show the notification_.

**Comment by jitendra1607** [comment]
Thank you for your insights. I am web developer so I understood your point but find it hard to override thing in java. Can you post sample code so that we can have sound also like native app?

**Comment by beverloo** [comment]
I don't have any unfortunately, but perhaps @andreban is aware of examples?

**Comment by jitendra1607** [comment]
Thank you. @andreban can you help me please?

**Comment by andreban** [comment]
I'll work on adding a demo to android-browser-helper and created https://github.com/GoogleChrome/android-browser-helper/issues/91 to track that.

If custom sounds are something we see developers looking for frequently, we can add support to enable it by configuration on the default delegation service.

**Comment by jitendra1607** [comment]
@andreban Thank you sir.

**Comment by andreban** [comment]
I created a PR for a Notification Delegation demo (with custom sound) here: https://github.com/GoogleChrome/android-browser-helper/pull/93

**Comment by jitendra1607** [comment]
@andreban Great, i will try it now.

**Comment by CVeniamin** [comment]
@andreban, thank you for making that example! 
I gave it a go, however for some reason Chrome browser would still handle the notification and the `onNotifyNotificationWithChannel` method in`NotificationDelegationService` does not seem to be called. I also attempted to change the channel name as per the comment in the https://github.com/GoogleChrome/android-browser-helper/pull/93. Could be possible that there was a change from Chrome team that made impossible to enable sounds?

NB: I checked both my TWA App settings and Chrome site settings to see if sound permission in notification are enabled and both seem to be. I am aware that currently no browser supports the sound property in web-push but really hoped that your example would fix that :)
