### ISSUE TITLE
Reduce size of the app 😂

### ISSUE THREAD

**Issue by happylolonly** [GoogleChromeLabs/svgomg-twa#69]
Hi everyone, it is possible to reduce a size TWA from 500-700kb to, for example, 150kb ?
Fight for web;)

What need to do?

I had ~650kb, changed icon and splash screen, now ~750kb...
https://play.google.com/store/apps/details?id=by.freefitness.app

**Comment by happylolonly** [comment]
TWA preload whole PWA?
How much % Android code in it?

**Comment by PEConn** [comment]
Hey,

I've had a brief look into this but not found any low hanging fruit. It appears that there's a bunch of resources pulled in by the Android Support Library (things like themes and icons). This project already has Proguard enabled, so the next step is to find out why these resources are still being included (since as far as I can tell they're not used).

If you fancy having a try yourself there's some info [here](https://developer.android.com/studio/build/shrink-code) (especially the last section about troubleshooting), otherwise Andre or I will get to it when time/priority allows.

**Comment by andreban** [comment]
Closing this in favour of tracking in llama-pack: https://github.com/GoogleChromeLabs/llama-pack/issues/107
