### ISSUE TITLE
Default Version Name within Build.Gradle file

### ISSUE THREAD

**Issue by matthewhartman** [GoogleChromeLabs/svgomg-twa#77]
Really minor one (might not be worth changing, just something to be cautious of) is the versionName and versionCode within:
`/app/build.gradle/`

* versionName is set to `2.0.0` - worth setting to `1.0.0` ?
* versionName is set to `3` - worth setting to `1` ?

Thanks. :)

**Comment by andreban** [comment]
Hey Matthew,

Thanks for filing this. We have been updating the versions when we update the template. The reason is that if a developer is upgrading their app using the new template, the version numbers will be correct.

Fell free change it to versionName 1.0.0 and versionCode 1, if you are starting a new app.

Andre

**Comment by matthewhartman** [comment]
No problems. Thanks Andre! 👌
