### ISSUE TITLE
Google Play Billing

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [GoogleChromeLabs/svgomg-twa#83]
Just found https://github.com/GoogleChrome/android-browser-helper/tree/master/playbilling, but how to use it?

**Comment by andreban** [comment]
The `playbilling` component is experimental and is still missing the counterpart implementation on the browser side. The API is still subject to change too.

**Comment by ramonwanderley** [comment]
Any predictions to officially release?

**Comment by shakazullu94** [comment]
@andreban Hi, any updates on this?

Since google decided to ditch [3rd party billings](https://techcrunch.com/2020/09/28/google-play-to-better-enforce-in-app-purchase-policies-ease-use-of-third-party-android-app-stores/) in upcoming period, I believe this became even bigger questions to some of us..

I've made some research and found your answers around web eg. (https://stackoverflow.com/questions/59881544/how-to-implement-play-store-purchases-from-a-trusted-web-activity).. 

I would really appreciate if you could navigate me more about this.

**Comment by andreban** [comment]
This repository is deprecated and we're not actively reading new issues here. You will be interested in https://github.com/GoogleChrome/android-browser-helper/issues/170.
