### ISSUE TITLE
TWA Throwing Error - java.util.concurrent.TimeoutException  android.os.Parcel.nativeDestroy

### ISSUE THREAD

**Issue by naveedahmed1** [GoogleChromeLabs/svgomg-twa#97]
I am seeing crash reports in Play Console with latest version of TWA which is based on svgomg-twa

```
java.util.concurrent.TimeoutException: 
  at android.os.Parcel.nativeDestroy (Parcel.java)
  at android.os.Parcel.destroy (Parcel.java:2490)
  at android.os.Parcel.finalize (Parcel.java:2503)
  at java.lang.Daemons$FinalizerDaemon.doFinalize (Daemons.java:198)
  at java.lang.Daemons$FinalizerDaemon.run (Daemons.java:177)
  at java.lang.Thread.run (Thread.java:818)
```

**Comment by andreban** [comment]
This is an issue on the Chrome / Support Library side. Can you please file on issue on bugs.chromium.org using this template? Please, also add any information about the device,  android version, android-browser-helper version and browser versions you have. I'll close the issue here in favour of the one filed there. Thank You.

**Comment by naveedahmed1** [comment]
Thank you @andreban I have posted it here https://bugs.chromium.org/p/chromium/issues/detail?id=1054744

**Comment by naveedahmed1** [comment]
Can you please also assign component component:UI>Browser>Mobile>TrustedWebActivities to this issue as well:

https://bugs.chromium.org/p/chromium/issues/detail?id=1054745

**Comment by andreban** [comment]
done

**Comment by naveedahmed1** [comment]
Thank you so much :)
