### ISSUE TITLE
Change android launcher behavior

### ISSUE THREAD

**Issue by Oli22** [GoogleChromeLabs/svgomg-twa#99]
Every time I launch the app from the Android launcher I am redirected to the launchUrl set in the twaManifest. That's no good behavior for actually using the app. Imagine the User looking for example at his shopping cart, he moves into another app and thereafter wants to go into the TWA again. If he does it via the app switcher everything works as expected, but if he clicks on the icon the launchUrl is called and he loses his current app state.

Is it possible to prevent this behavior and only launch to the launchUrl if the app was closed via the app switcher?

I have looked everywhere and found no solution, even all the easy TWAs I found on the Google Play Store have this bad behavior.
Thanks in advance for your help!

**Comment by andreban** [comment]
This is  an issue on the Chrome / Support Library side.  Can you please file on issue on bugs.chromium.org using this [template](https://bugs.chromium.org/p/chromium/issues/entry?components=UI%3EBrowser%3EMobile%3ETrustedWebActivities)? Please, also add information about the device you are using and Chrome version. I'll close the issue here in favour of the one filed there. Thank You.
